---

- name: Add group
  group:
    name: hello
    state: present

- name: Add user
  user:
    name: deploy
    group: hello

- name: Move test file
  copy:
    src: "{{ move_test_file }}"
    dest: "/test.txt"
